spring:
   application:
    name: gateway
cloud:
    gateway:
      routes:
        - id: HOME
          uri: lb://HOME
          predicates:
            - Path=/home
        - id:
          uri: lb://BANKOMATI-SERVICE
          predicates:
            - Path=/select/**
        - id: CITIES
          uri: lb://CITIES-DETAILS
          predicates:
            - Path=/selectType
        - id: SHOW-DETAILS
          uri: lb://DETAILS
          predicates:
            - Path=/showDetails